<?php

namespace App\Models;

use App\Enums\Outreach\OutreachChannel;
use App\Enums\Outreach\OutreachStatus;
use Database\Factories\OutreachAttemptFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\MorphMany;

#[Fillable([
    'contact_id',
    'channel',
    'subject',
    'message',
    'status',
    'sent_at',
    'responded_at',
    'notes',
])]
class OutreachAttempt extends Model
{
    /** @use HasFactory<OutreachAttemptFactory> */
    use HasFactory;

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'channel' => OutreachChannel::class,
            'status' => OutreachStatus::class,
            'sent_at' => 'datetime',
            'responded_at' => 'datetime',
        ];
    }

    /**
     * Contact this outreach attempt belongs to.
     */
    public function contact(): BelongsTo
    {
        return $this->belongsTo(Contact::class);
    }

    /**
     * Determine whether this outreach attempt has received a response.
     */
    public function hasResponse(): bool
    {
        return $this->responded_at !== null;
    }

    /**
     * Activities generated by this outreach attempt.
     */
    public function activities(): MorphMany
    {
        return $this->morphMany(Activity::class, 'subject');
    }
}
